#!/usr/bin/env python3
"""
Reels Auto Creator
Auto-generated by OmniFlow Factory
Uses HuggingFace Inference API (FREE)
"""

import os
import json
import time
import requests
from datetime import datetime

# ============================================
# CONFIGURATION - HUGGINGFACE
# ============================================
HUGGINGFACE_TOKEN = os.getenv('HUGGINGFACE_TOKEN', '')
HF_API_URL = "https://router.huggingface.co/v1/chat/completions"
HF_MODEL = "google/gemma-2-2b-it"  # Free model

SYSTEM_CONTEXT = """
Runway, D-ID, ElevenLabs, Instagram API
Focus: Hairdresser, Beauty Salon, Hair Trends, Transformations, Balayage, Ombre, Hair Care
"""

def call_huggingface(prompt: str) -> str:
    """Call HuggingFace Inference API"""
    if not HUGGINGFACE_TOKEN:
        print("⚠️ Warning: HUGGINGFACE_TOKEN is not set. Using dummy response.")
        return "Simulation: Content would be generated here."
    
    headers = {
        "Authorization": f"Bearer {HUGGINGFACE_TOKEN}",
        "Content-Type": "application/json"
    }
    
    payload = {
        "model": HF_MODEL,
        "messages": [{"role": "user", "content": prompt}],
        "max_tokens": 1024,
        "temperature": 0.7
    }
    
    try:
        response = requests.post(HF_API_URL, headers=headers, json=payload, timeout=120)
        response.raise_for_status()
        data = response.json()
        
        if "choices" in data and len(data["choices"]) > 0:
            return data["choices"][0]["message"]["content"]
        return str(data)
    except Exception as e:
        return f"Error: {e}"

# ============================================
# WORKFLOW NODES
# ============================================

def node_0_rac_1(input_data: str) -> str:
    """
    Node: Günlük Tetikle
    Role: Cron
    Type: vault_node
    """
    print(f"⚙️ Running: Günlük Tetikle")
    
    prompt = f"""
Role: Cron
Task: Her gün yeni Reel
Context: {SYSTEM_CONTEXT}
Input: {input_data}

Execute the task and provide detailed output.
"""
    
    result = call_huggingface(prompt)
    print(f"✅ Günlük Tetikle completed")
    return result


def node_1_rac_2(input_data: str) -> str:
    """
    Node: Viral Trend Bul
    Role: TikTok Scraper
    Type: research
    """
    print(f"⚙️ Running: Viral Trend Bul")
    
    prompt = f"""
Role: TikTok Scraper
Task: Viral formatları analiz et
Context: {SYSTEM_CONTEXT}
Input: {input_data}

Execute the task and provide detailed output.
"""
    
    result = call_huggingface(prompt)
    print(f"✅ Viral Trend Bul completed")
    return result


def node_2_rac_3(input_data: str) -> str:
    """
    Node: Script Yaz
    Role: GPT-4
    Type: creator
    """
    print(f"⚙️ Running: Script Yaz")
    
    prompt = f"""
Role: GPT-4
Task: 15-60 saniyelik script
Context: {SYSTEM_CONTEXT}
Input: {input_data}

Execute the task and provide detailed output.
"""
    
    result = call_huggingface(prompt)
    print(f"✅ Script Yaz completed")
    return result


def node_3_rac_4(input_data: str) -> str:
    """
    Node: Video Oluştur
    Role: Runway/D-ID
    Type: video
    """
    print(f"⚙️ Running: Video Oluştur")
    
    prompt = f"""
Role: Runway/D-ID
Task: AI video render
Context: {SYSTEM_CONTEXT}
Input: {input_data}

Execute the task and provide detailed output.
"""
    
    result = call_huggingface(prompt)
    print(f"✅ Video Oluştur completed")
    return result


def node_4_rac_5(input_data: str) -> str:
    """
    Node: Seslendirme
    Role: ElevenLabs
    Type: media
    """
    print(f"⚙️ Running: Seslendirme")
    
    prompt = f"""
Role: ElevenLabs
Task: AI voiceover ekle
Context: {SYSTEM_CONTEXT}
Input: {input_data}

Execute the task and provide detailed output.
"""
    
    result = call_huggingface(prompt)
    print(f"✅ Seslendirme completed")
    return result


def node_5_rac_6(input_data: str) -> str:
    """
    Node: Müzik Ekle
    Role: Audio Mix
    Type: media
    """
    print(f"⚙️ Running: Müzik Ekle")
    
    prompt = f"""
Role: Audio Mix
Task: Trending müzik overlay
Context: {SYSTEM_CONTEXT}
Input: {input_data}

Execute the task and provide detailed output.
"""
    
    result = call_huggingface(prompt)
    print(f"✅ Müzik Ekle completed")
    return result


def node_6_rac_7(input_data: str) -> str:
    """
    Node: 🚀 REEL YAYINLA
    Role: Instagram API
    Type: social
    """
    print(f"⚙️ Running: 🚀 REEL YAYINLA")
    
    prompt = f"""
Role: Instagram API
Task: Reels olarak paylaş
Context: {SYSTEM_CONTEXT}
Input: {input_data}

Execute the task and provide detailed output.
"""
    
    result = call_huggingface(prompt)
    print(f"✅ 🚀 REEL YAYINLA completed")
    return result


# ============================================
# TELEGRAM NOTIFICATION (Optional)
# ============================================
def send_telegram(message: str):
    bot_token = os.getenv('TELEGRAM_BOT_TOKEN', '')
    chat_id = os.getenv('TELEGRAM_CHAT_ID', '')
    if bot_token and chat_id:
        try:
            url = f"https://api.telegram.org/bot{bot_token}/sendMessage"
            requests.post(url, json={"chat_id": chat_id, "text": message[:4000]})
            print("📱 Telegram sent")
        except: pass

# ============================================
# MAIN EXECUTION
# ============================================
def run_workflow(initial_input: str = "Tiktok Viral Hairdresser Trends"):
    """Execute the complete workflow"""
    print("=" * 50)
    print(f"🚀 Starting: Reels Auto Creator (Hairdresser Edition)")
    print(f"📅 {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}")
    print("=" * 50)
    
    current_output = initial_input
    results = {}
    
    # Step 1: Günlük Tetikle
    results['rac-1'] = node_0_rac_1(current_output)
    current_output = results['rac-1']
    time.sleep(2)  # Rate limiting

    # Step 2: Viral Trend Bul
    results['rac-2'] = node_1_rac_2(current_output)
    current_output = results['rac-2']
    time.sleep(2)  # Rate limiting

    # Step 3: Script Yaz
    results['rac-3'] = node_2_rac_3(current_output)
    current_output = results['rac-3']
    time.sleep(2)  # Rate limiting

    # Step 4: Video Oluştur
    results['rac-4'] = node_3_rac_4(current_output)
    current_output = results['rac-4']
    time.sleep(2)  # Rate limiting

    # Step 5: Seslendirme
    results['rac-5'] = node_4_rac_5(current_output)
    current_output = results['rac-5']
    time.sleep(2)  # Rate limiting

    # Step 6: Müzik Ekle
    results['rac-6'] = node_5_rac_6(current_output)
    current_output = results['rac-6']
    time.sleep(2)  # Rate limiting

    # Step 7: 🚀 REEL YAYINLA
    results['rac-7'] = node_6_rac_7(current_output)
    current_output = results['rac-7']
    time.sleep(2)  # Rate limiting

    
    print("\n" + "=" * 50)
    print("✅ Workflow completed!")
    print("=" * 50)
    
    # Send notification
    send_telegram(f"✅ (Kuaför) Reels Auto Creator tamamlandı!\n\n{current_output[:500]}...")
    
    return results

if __name__ == "__main__":
    import sys
    initial = sys.argv[1] if len(sys.argv) > 1 else "Generate Viral Hairdresser Content"
    results = run_workflow(initial)
    
    # Save results
    output_file = f"results_{datetime.now().strftime('%Y%m%d_%H%M%S')}.json"
    with open(output_file, 'w', encoding='utf-8') as f:
        json.dump(results, f, ensure_ascii=False, indent=2)
    print(f"\n📄 Results saved to {output_file}")
