#!/usr/bin/env python3
"""
İçerik Fabrikası
Auto-generated by OmniFlow Factory
Modified to use HuggingFace API (Free)
"""

import os
import json
import time
import requests
from datetime import datetime

# ============================================
# CONFIGURATION
# ============================================
HUGGINGFACE_TOKEN = os.getenv('HUGGINGFACE_TOKEN', '')
HF_API_URL = "https://router.huggingface.co/v1/chat/completions"
HF_MODEL = "google/gemma-2-2b-it"  # Free model

SYSTEM_CONTEXT = """
Trend analizi, copywriting, görsel tasarım
"""

def call_huggingface(prompt: str) -> str:
    """Call HuggingFace Inference API"""
    if not HUGGINGFACE_TOKEN:
        return "Error: HUGGINGFACE_TOKEN not set"
    
    headers = {
        "Authorization": f"Bearer {HUGGINGFACE_TOKEN}",
        "Content-Type": "application/json"
    }
    
    payload = {
        "model": HF_MODEL,
        "messages": [
            {"role": "user", "content": prompt}
        ],
        "max_tokens": 1024,
        "temperature": 0.7
    }
    
    try:
        response = requests.post(HF_API_URL, headers=headers, json=payload, timeout=120)
        response.raise_for_status()
        data = response.json()
        
        if "choices" in data and len(data["choices"]) > 0:
            return data["choices"][0]["message"]["content"]
        return str(data)
    except Exception as e:
        return f"Error: {e}"

# ============================================
# WORKFLOW NODES
# ============================================

def node_0_trend_tarayici(input_data: str) -> str:
    """Node: Trend Tarayıcı - Twitter/Instagram trendlerini bul"""
    print(f"⚙️ Running: Trend Tarayıcı")
    
    prompt = f"""Sen bir sosyal medya trend analistisin.
Rol: Twitter/Instagram Trend Analisti
Görev: Günün viral trendlerini bul ve listele

Bağlam: {SYSTEM_CONTEXT}
Girdi: {input_data}

Şu anki popüler trendleri, hashtagleri ve viral konuları listele.
Türkiye'ye odaklan.
"""
    
    result = call_huggingface(prompt)
    print(f"✅ Trend Tarayıcı completed")
    return result


def node_1_firsat_analizi(input_data: str) -> str:
    """Node: Fırsat Analizi - Markayla uyumlu trendleri filtrele"""
    print(f"⚙️ Running: Fırsat Analizi")
    
    prompt = f"""Sen bir marka stratejistisin.
Rol: AI Fırsat Analisti
Görev: Bu trendlerden marka için uygun olanları seç

Bağlam: {SYSTEM_CONTEXT}
Trendler: {input_data}

En uygun 3 trendi seç ve neden uygun olduklarını açıkla.
"""
    
    result = call_huggingface(prompt)
    print(f"✅ Fırsat Analizi completed")
    return result


def node_2_metin_yazari(input_data: str) -> str:
    """Node: Metin Yazarı - Platformlara özel caption yaz"""
    print(f"⚙️ Running: Metin Yazarı")
    
    prompt = f"""Sen profesyonel bir copywriter'sın.
Rol: Sosyal Medya Copywriter
Görev: Her platform için özel içerik yaz

Seçilen Trendler: {input_data}

Her biri için:
1. Instagram caption (emoji dahil)
2. Twitter post (280 karakter)
3. LinkedIn paylaşımı

Hashtag önerileri de ekle.
"""
    
    result = call_huggingface(prompt)
    print(f"✅ Metin Yazarı completed")
    return result


def node_3_gorsel_onerici(input_data: str) -> str:
    """Node: Görsel Önerici - Görsel konsepti ve prompt oluştur"""
    print(f"⚙️ Running: Görsel Önerici")
    
    prompt = f"""Sen bir görsel tasarımcısın.
Rol: Design AI
Görev: İçerikler için görsel konsepti oluştur

İçerikler: {input_data}

Her içerik için:
1. Görsel konsepti açıkla
2. Renk paleti öner
3. AI görsel üretimi için İngilizce prompt yaz (Midjourney/DALL-E formatında)
"""
    
    result = call_huggingface(prompt)
    print(f"✅ Görsel Önerici completed")
    return result


def node_4_icerik_paketi(input_data: str) -> str:
    """Node: İçerik Paketi - Hazır paylaşım paketi oluştur"""
    print(f"⚙️ Running: İçerik Paketi")
    
    prompt = f"""Sen bir içerik yöneticisisin.
Rol: Content Manager
Görev: Tüm içerikleri düzenli bir pakete hazırla

Tüm Çıktılar: {input_data}

Final paketi oluştur:
1. 📅 Paylaşım takvimi (hangi gün, hangi saat)
2. 📝 Platform bazlı içerikler
3. 🎨 Görsel notları
4. #️⃣ Hashtag grupları
5. 📊 Beklenen performans
"""
    
    result = call_huggingface(prompt)
    print(f"✅ İçerik Paketi completed")
    return result


# ============================================
# NOTIFICATION (Optional)
# ============================================
def send_telegram_notification(message: str):
    """Send result to Telegram"""
    bot_token = os.getenv('TELEGRAM_BOT_TOKEN', '')
    chat_id = os.getenv('TELEGRAM_CHAT_ID', '')
    
    if not bot_token or not chat_id:
        print("⚠️ Telegram not configured")
        return
    
    try:
        url = f"https://api.telegram.org/bot{bot_token}/sendMessage"
        payload = {
            "chat_id": chat_id,
            "text": message[:4000],  # Telegram limit
            "parse_mode": "Markdown"
        }
        requests.post(url, json=payload)
        print("📱 Telegram notification sent")
    except Exception as e:
        print(f"❌ Telegram error: {e}")


# ============================================
# MAIN EXECUTION
# ============================================
def run_workflow(initial_input: str = "Start"):
    """Execute the complete workflow"""
    print("=" * 50)
    print(f"🚀 Starting: İçerik Fabrikası")
    print(f"📅 {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}")
    print("=" * 50)
    
    current_output = initial_input
    results = {}
    
    # Step 1: Trend Tarayıcı
    results['trend_tarayici'] = node_0_trend_tarayici(current_output)
    current_output = results['trend_tarayici']
    time.sleep(2)  # Rate limiting

    # Step 2: Fırsat Analizi
    results['firsat_analizi'] = node_1_firsat_analizi(current_output)
    current_output = results['firsat_analizi']
    time.sleep(2)

    # Step 3: Metin Yazarı
    results['metin_yazari'] = node_2_metin_yazari(current_output)
    current_output = results['metin_yazari']
    time.sleep(2)

    # Step 4: Görsel Önerici
    results['gorsel_onerici'] = node_3_gorsel_onerici(current_output)
    current_output = results['gorsel_onerici']
    time.sleep(2)

    # Step 5: İçerik Paketi
    results['icerik_paketi'] = node_4_icerik_paketi(current_output)
    
    print("\n" + "=" * 50)
    print("✅ Workflow completed!")
    print("=" * 50)
    
    # Send notification
    summary = f"""🎉 *İçerik Fabrikası Tamamlandı!*

📅 {datetime.now().strftime('%Y-%m-%d %H:%M')}

📦 *İçerik Paketi:*
{results['icerik_paketi'][:1000]}...
"""
    send_telegram_notification(summary)
    
    return results


if __name__ == "__main__":
    import sys
    initial = sys.argv[1] if len(sys.argv) > 1 else "Güncel trendleri tara ve içerik paketi oluştur"
    results = run_workflow(initial)
    
    # Save results
    output_file = f"icerik_fabrikasi_{datetime.now().strftime('%Y%m%d_%H%M%S')}.json"
    with open(output_file, 'w', encoding='utf-8') as f:
        json.dump(results, f, ensure_ascii=False, indent=2)
    print(f"\n📄 Results saved to {output_file}")
