#!/usr/bin/env python3
"""
Blog Yazısı Üretici
AI ile SEO uyumlu blog yazısı üretir

Auto-generated by OmniFlow Factory
"""

# Auto-generated API Connectors
import requests
import os
from dotenv import load_dotenv
load_dotenv()

def huggingface_generate(prompt: str, model: str = "mistralai/Mistral-7B-Instruct-v0.2") -> str:
    """HuggingFace ile metin üret"""
    API_URL = f"https://api-inference.huggingface.co/models/{model}"
    headers = {"Authorization": f"Bearer {os.getenv('HUGGINGFACE_TOKEN')}"}
    
    payload = {
        "inputs": prompt,
        "parameters": {
            "max_new_tokens": 500,
            "temperature": 0.7,
            "top_p": 0.9,
            "do_sample": True
        }
    }
    
    response = requests.post(API_URL, headers=headers, json=payload)
    if response.status_code == 200:
        result = response.json()
        if isinstance(result, list) and len(result) > 0:
            return result[0].get('generated_text', '').replace(prompt, '').strip()
    return ""

# ============================================
# MAIN AUTOMATION CODE
# ============================================

def generate_blog_post(topic: str, keywords: list = None) -> dict:
    """Blog yazısı üret"""
    keyword_str = ", ".join(keywords) if keywords else ""
    
    prompt = f"""Bir blog yazısı yaz:
Konu: {topic}
Anahtar kelimeler: {keyword_str}

Format:
# [Başlık]

[Giriş paragrafı]

## [Alt Başlık 1]
[İçerik]

## [Alt Başlık 2]
[İçerik]

## Sonuç
[Sonuç paragrafı]

---
Yazı profesyonel, SEO uyumlu ve 500-800 kelime olmalı.
"""
    
    content = huggingface_generate(prompt)
    
    return {
        "topic": topic,
        "content": content,
        "keywords": keywords,
        "word_count": len(content.split())
    }

if __name__ == "__main__":
    import sys
    topic = sys.argv[1] if len(sys.argv) > 1 else "Yapay Zeka ve Gelecek"
    keywords = sys.argv[2].split(",") if len(sys.argv) > 2 else ["AI", "teknoloji", "gelecek"]
    
    print("🚀 Blog yazısı üretiliyor...")
    result = generate_blog_post(topic, keywords)
    print("=" * 50)
    print(f"📝 Konu: {result['topic']}")
    print(f"📊 Kelime sayısı: {result['word_count']}")
    print("=" * 50)
    print(result['content'])
