#!/usr/bin/env python3
"""
AI Email Yanıtlayıcı
Gelen emaillere AI ile profesyonel yanıt üretir

Auto-generated by OmniFlow Factory
"""

import requests
import os
import smtplib
from email.mime.text import MIMEText
from email.mime.multipart import MIMEMultipart
from dotenv import load_dotenv
load_dotenv()

def huggingface_generate(prompt: str, model: str = "mistralai/Mistral-7B-Instruct-v0.2") -> str:
    """HuggingFace ile metin üret"""
    API_URL = f"https://api-inference.huggingface.co/models/{model}"
    headers = {"Authorization": f"Bearer {os.getenv('HUGGINGFACE_TOKEN')}"}
    
    payload = {
        "inputs": prompt,
        "parameters": {
            "max_new_tokens": 400,
            "temperature": 0.7,
            "top_p": 0.9,
            "do_sample": True
        }
    }
    
    response = requests.post(API_URL, headers=headers, json=payload)
    if response.status_code == 200:
        result = response.json()
        if isinstance(result, list) and len(result) > 0:
            return result[0].get('generated_text', '').replace(prompt, '').strip()
    return ""

def send_email(to: str, subject: str, body: str) -> bool:
    """Email gönder"""
    try:
        msg = MIMEMultipart()
        msg['From'] = os.getenv('SMTP_FROM')
        msg['To'] = to
        msg['Subject'] = subject
        msg.attach(MIMEText(body, 'html'))
        
        server = smtplib.SMTP(os.getenv('SMTP_HOST'), int(os.getenv('SMTP_PORT', 587)))
        server.starttls()
        server.login(os.getenv('SMTP_USER'), os.getenv('SMTP_PASS'))
        server.send_message(msg)
        server.quit()
        return True
    except Exception as e:
        print(f"Email hatası: {e}")
        return False

# ============================================
# MAIN AUTOMATION CODE
# ============================================

def generate_email_response(original_email: str, context: str = "") -> dict:
    """Email yanıtı üret"""
    
    prompt = f"""Aşağıdaki emaile profesyonel bir yanıt yaz:

GELEN EMAIL:
{original_email}

EK BAĞLAM:
{context if context else "Yok"}

Kurallar:
1. Profesyonel ve nazik ol
2. Soruları cevapla
3. Gerekirse ek bilgi iste
4. İmza ekle

Format:
Merhaba,

[yanıt içeriği]

Saygılarımla,
[Şirket Adı]
"""
    
    response = huggingface_generate(prompt)
    
    return {
        "original": original_email[:200] + "..." if len(original_email) > 200 else original_email,
        "response": response,
        "word_count": len(response.split())
    }

def respond_and_send(to: str, subject: str, original_email: str, context: str = "") -> dict:
    """Yanıt üret ve gönder"""
    
    result = generate_email_response(original_email, context)
    
    # Email gönder (SMTP ayarları varsa)
    if os.getenv('SMTP_HOST'):
        success = send_email(to, f"Re: {subject}", result['response'])
    else:
        success = False
        print("⚠️ SMTP ayarları yapılmamış, email gönderilmedi.")
    
    return {
        **result,
        "sent": success,
        "to": to,
        "subject": f"Re: {subject}"
    }

if __name__ == "__main__":
    # Test modu - sadece yanıt üret, gönderme
    test_email = """
Merhaba,

Ürününüzle ilgileniyorum. Fiyat ve teslimat süresi hakkında bilgi alabilir miyim?

Teşekkürler,
Ahmet
"""
    
    print("🚀 Email yanıtı üretiliyor...")
    result = generate_email_response(test_email, "E-ticaret sitesi, dijital ürün satışı")
    print("=" * 50)
    print("📧 EMAIL YANITI")
    print("=" * 50)
    print(result['response'])
    print(f"\n({result['word_count']} kelime)")
