#!/usr/bin/env python3
"""
Etsy SEO Açıklama Üretici
Etsy ürün başlığı, açıklaması ve tag'leri üretir

Auto-generated by OmniFlow Factory
"""

import requests
import os
from dotenv import load_dotenv
load_dotenv()

def huggingface_generate(prompt: str, model: str = "mistralai/Mistral-7B-Instruct-v0.2") -> str:
    """HuggingFace ile metin üret"""
    API_URL = f"https://api-inference.huggingface.co/models/{model}"
    headers = {"Authorization": f"Bearer {os.getenv('HUGGINGFACE_TOKEN')}"}
    
    payload = {
        "inputs": prompt,
        "parameters": {
            "max_new_tokens": 500,
            "temperature": 0.7,
            "top_p": 0.9,
            "do_sample": True
        }
    }
    
    response = requests.post(API_URL, headers=headers, json=payload)
    if response.status_code == 200:
        result = response.json()
        if isinstance(result, list) and len(result) > 0:
            return result[0].get('generated_text', '').replace(prompt, '').strip()
    return ""

# ============================================
# MAIN AUTOMATION CODE
# ============================================

def generate_etsy_listing(product: str, category: str = "dijital ürün") -> dict:
    """Etsy listing içeriği üret"""
    
    prompt = f"""Etsy için ürün listesi oluştur:
Ürün: {product}
Kategori: {category}

Oluştur:
1. SEO uyumlu başlık (140 karakter max, anahtar kelimelerle)
2. Detaylı açıklama (ürün özellikleri, kullanım, neden almalı)
3. 13 adet SEO tag (virgülle ayır)

Format:
BAŞLIK: [başlık]

AÇIKLAMA:
[açıklama]

TAG'LER: tag1, tag2, tag3, ...
"""
    
    content = huggingface_generate(prompt)
    
    # Parse et
    lines = content.strip().split("\n")
    title = ""
    description_lines = []
    tags = []
    current_section = None
    
    for line in lines:
        line = line.strip()
        if line.upper().startswith("BAŞLIK:") or line.upper().startswith("TITLE:"):
            title = line.split(":", 1)[1].strip() if ":" in line else ""
            current_section = "title"
        elif line.upper().startswith("AÇIKLAMA:") or line.upper().startswith("DESCRIPTION:"):
            current_section = "description"
        elif line.upper().startswith("TAG") or line.upper().startswith("ETIKET"):
            if ":" in line:
                tags = [tag.strip() for tag in line.split(":", 1)[1].split(",")]
            current_section = "tags"
        elif current_section == "description" and line:
            description_lines.append(line)
    
    return {
        "product": product,
        "title": title[:140],
        "description": "\n".join(description_lines),
        "tags": tags[:13],
        "tag_count": len(tags[:13])
    }

if __name__ == "__main__":
    import sys
    product = sys.argv[1] if len(sys.argv) > 1 else "Dijital Planner 2024"
    category = sys.argv[2] if len(sys.argv) > 2 else "dijital ürün"
    
    print("🚀 Etsy listing üretiliyor...")
    result = generate_etsy_listing(product, category)
    print("=" * 50)
    print("🛍️ ETSY LISTING")
    print("=" * 50)
    print(f"\nBAŞLIK ({len(result['title'])} karakter):")
    print(result['title'])
    print(f"\nAÇIKLAMA:")
    print(result['description'])
    print(f"\nTAG'LER ({result['tag_count']} adet):")
    print(", ".join(result['tags']))
