#!/usr/bin/env python3
"""
Instagram Caption Üretici
Viral Instagram caption ve hashtag üretir

Auto-generated by OmniFlow Factory
"""

import requests
import os
from dotenv import load_dotenv
load_dotenv()

def huggingface_generate(prompt: str, model: str = "mistralai/Mistral-7B-Instruct-v0.2") -> str:
    """HuggingFace ile metin üret"""
    API_URL = f"https://api-inference.huggingface.co/models/{model}"
    headers = {"Authorization": f"Bearer {os.getenv('HUGGINGFACE_TOKEN')}"}
    
    payload = {
        "inputs": prompt,
        "parameters": {
            "max_new_tokens": 300,
            "temperature": 0.8,
            "top_p": 0.9,
            "do_sample": True
        }
    }
    
    response = requests.post(API_URL, headers=headers, json=payload)
    if response.status_code == 200:
        result = response.json()
        if isinstance(result, list) and len(result) > 0:
            return result[0].get('generated_text', '').replace(prompt, '').strip()
    return ""

# ============================================
# MAIN AUTOMATION CODE
# ============================================

def generate_instagram_caption(theme: str, tone: str = "eğlenceli") -> dict:
    """Instagram caption üret"""
    
    prompt = f"""Instagram için viral bir caption yaz:
Tema: {theme}
Ton: {tone}

Kurallar:
1. Hook cümlesi ile başla (dikkat çekici)
2. Değer kat veya hikaye anlat
3. Call-to-action ekle
4. 5-10 alakalı hashtag ekle
5. 1-2 emoji kullan

Format:
[Caption metni]

#hashtag1 #hashtag2 #hashtag3 ...
"""
    
    content = huggingface_generate(prompt)
    
    # Hashtag'leri ayır
    lines = content.strip().split("\n")
    caption_lines = []
    hashtags = []
    
    for line in lines:
        if line.strip().startswith("#"):
            hashtags.extend([tag.strip() for tag in line.split() if tag.startswith("#")])
        else:
            caption_lines.append(line)
    
    return {
        "theme": theme,
        "caption": "\n".join(caption_lines).strip(),
        "hashtags": hashtags,
        "hashtag_count": len(hashtags)
    }

if __name__ == "__main__":
    import sys
    theme = sys.argv[1] if len(sys.argv) > 1 else "girişimcilik ve motivasyon"
    tone = sys.argv[2] if len(sys.argv) > 2 else "ilham verici"
    
    print("🚀 Instagram caption üretiliyor...")
    result = generate_instagram_caption(theme, tone)
    print("=" * 50)
    print("📸 INSTAGRAM CAPTION")
    print("=" * 50)
    print(result['caption'])
    print("")
    print(" ".join(result['hashtags']))
    print(f"\n({result['hashtag_count']} hashtag)")
