#!/usr/bin/env python3
"""
Tweet/X Post Üretici
Viral tweet ve thread üretir

Auto-generated by OmniFlow Factory
"""

import requests
import os
from dotenv import load_dotenv
load_dotenv()

def huggingface_generate(prompt: str, model: str = "mistralai/Mistral-7B-Instruct-v0.2") -> str:
    """HuggingFace ile metin üret"""
    API_URL = f"https://api-inference.huggingface.co/models/{model}"
    headers = {"Authorization": f"Bearer {os.getenv('HUGGINGFACE_TOKEN')}"}
    
    payload = {
        "inputs": prompt,
        "parameters": {
            "max_new_tokens": 300,
            "temperature": 0.8,
            "top_p": 0.9,
            "do_sample": True
        }
    }
    
    response = requests.post(API_URL, headers=headers, json=payload)
    if response.status_code == 200:
        result = response.json()
        if isinstance(result, list) and len(result) > 0:
            return result[0].get('generated_text', '').replace(prompt, '').strip()
    return ""

# ============================================
# MAIN AUTOMATION CODE
# ============================================

def generate_tweet(topic: str, style: str = "bilgilendirici") -> dict:
    """Tweet üret"""
    
    prompt = f"""Twitter/X için viral bir tweet yaz:
Konu: {topic}
Stil: {style}

Kurallar:
1. 280 karakter limiti
2. Dikkat çekici başla
3. Değer kat
4. Engagement tetikle (soru, tartışma)
5. 1-2 emoji kullan

Sadece tweet metnini yaz:
"""
    
    content = huggingface_generate(prompt)
    tweet = content.strip()[:280]
    
    return {
        "topic": topic,
        "tweet": tweet,
        "char_count": len(tweet),
        "style": style
    }

def generate_thread(topic: str, tweet_count: int = 5) -> dict:
    """Tweet thread üret"""
    
    prompt = f"""Twitter/X için {tweet_count} tweet'lik bir thread yaz:
Konu: {topic}

Kurallar:
1. Her tweet 280 karakter max
2. İlk tweet hook olmalı
3. Her tweet numaralı (1/, 2/, ...)
4. Son tweet CTA içermeli

Format:
1/ [tweet 1]
2/ [tweet 2]
...
"""
    
    content = huggingface_generate(prompt)
    tweets = []
    
    for line in content.strip().split("\n"):
        line = line.strip()
        if line and (line[0].isdigit() or line.startswith("🧵")):
            tweets.append(line[:280])
    
    return {
        "topic": topic,
        "tweets": tweets,
        "tweet_count": len(tweets)
    }

if __name__ == "__main__":
    import sys
    topic = sys.argv[1] if len(sys.argv) > 1 else "Yapay zeka ile para kazanmanın 5 yolu"
    mode = sys.argv[2] if len(sys.argv) > 2 else "tweet"  # tweet veya thread
    
    print("🚀 Tweet üretiliyor...")
    
    if mode == "thread":
        result = generate_thread(topic)
        print("=" * 50)
        print("🧵 TWITTER THREAD")
        print("=" * 50)
        for tweet in result['tweets']:
            print(f"\n{tweet}")
            print("-" * 30)
    else:
        result = generate_tweet(topic)
        print("=" * 50)
        print("🐦 TWEET")
        print("=" * 50)
        print(f"\n{result['tweet']}")
        print(f"\n({result['char_count']}/280 karakter)")
